<?php
//$this->headLink()->prependStylesheet('/css/booking-card.css');
$statusFormConfirm = $this->statusFormConfirm;
$statusFormReject = $this->statusFormReject;
$booking_card = $this->booking_card;
?>
<div class="booking-card-control">
    <ul class="booking-card">
        <form class="form-disabled">
            <li class="card-label">
                <div class="value"></div>
            </li>
            <li class="card-created_time">
                <div class="label">Создана:</div>
                <div class="value"></div>
            </li>
            <li class="card-name">
                <div class="label">ФИО:</div>
                <div class="value"></div>
                <input type="text" name="card-name" class="value">
            </li>
            <li class="card-phone">
                <div class="label">Телефон:</div>
                <div class="value"></div>
                <input type="text" name="card-phone" class="value">
            </li>
            <li class="card-email">
                <div class="label">E-mail:</div>
                <div class="value"></div>
                <input type="text" name="card-email" class="value">
            </li>
            <li class="card-message">
                <div class="label">Сообщение:</div>
                <div class="value"></div>
                <input type="text" name="card-message" class="value">
            </li>
            <li class="card-time">
                <div class="label">Заявка на:</div>
                <div class="value"></div>
                <input type="text" name="card-time" class="value">
            </li>

            <li class="are-you-sure">
                <div class="label">Вы уверены?</div>
                <div class="value">
                    <a class="btn btn-outline-secondary cancel">Отмена</a>
                </div>
            </li>
            <li class="card-buttons">
                <div>
                    <a class="btn btn-outline-success booking-approve" onclick="return false">Подтвердить</a>
                    <a class="btn btn-outline-danger booking-decline" onclick="return false">Отклонить</a>
                    <a class="btn btn-outline-secondary booking-edit">Редактировать
                        <div class="icon">
                            <div class="icon-title">
                                <img src="/img/icons/edit-icon.png" alt="edit-icon"/>
                            </div>
                            <div class="hint">
                                Оставить комментарий
                            </div>
                        </div>
                    </a>
                    <input type="submit" class="btn btn-outline-secondary booking-edit-complete"
                           value="Сохранить изменения">
                </div>
                <div class="anchor"><a></a></div>
            </li>
            </li>
        </form>
    </ul>
</div>


