<?php
$this->headTitle('Operator-menu');

//$this->headLink()->prependStylesheet('/build/operator_11e5.css');

?>

<div class="control-container">

    <?php echo $this->partial('application/operator/booking-card-filter'); ?>


    <div class="booking-card-list" id="list">
        <?php echo $this->partial('application/operator/booking-card'); ?>
    </div>
    <div class="logout-menu">
        <a href='/logout' class="btn btn-outline-secondary">Выход</a>
    </div>
</div>
