<?php
if (isset($this->loginForm)) {

    $loginForm = $this->loginForm;
    $loginForm->prepare();

    ?>

    <div class="login-form">
        <?= $this->form()->openTag($loginForm); ?>

        <div class="header">
            <div class="value">Вход:</div>
        </div>
        <div class="body">
            <div class="login">
                <?= $this->formLabel($loginForm->get('login')); ?>
                <?= $this->formElement($loginForm->get('login')); ?>
                <?= $this->formElementErrors($loginForm->get('login')); ?>
            </div>
            <div class="password">
                <?= $this->formLabel($loginForm->get('password')); ?>
                <?= $this->formElement($loginForm->get('password')); ?>
                <?= $this->formElementErrors($loginForm->get('password')); ?>
            </div>
            <div class="submit">
                <?= $this->formElement($loginForm->get('submit')); ?>
            </div>

            <?= $this->form()->closeTag(); ?>
        </div>
    </div>

    <?php
    if (isset($this->error_message)) {
        echo $this->error_message;
    }
}
?>