<?= $this->doctype() ?>

    <html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="Content-Type" content="text/html; charset=windows-1251"/>
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css?family=Roboto|Ubuntu|Nunito">

        <?= $this->headTitle('БрянскМАЗсервис')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        $operator_css = glob("public/build/operator_*.css");
        $operator_css = explode("/", $operator_css[0])[2];
        ?>

        <?=

        $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])

            ->prependStylesheet($this->basePath('build/' . $operator_css))
        //            ->prependStylesheet($this->basePath('css/base.css'))
        //            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <?php
        $operator_js = glob("public/build/operator_*.js");
        $operator_js = explode("/", $operator_js[0])[2];
        ?>


    </head>
    <body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container bg-light mt-5 ">

        </div>
    </nav>

    <div class="container">
        <?= $this->content ?>
        <hr>
        <footer>
            <p>&copy; 2005 - <?= date('Y') ?> БрянскМАЗсервис. Все права защищены.</p>
        </footer>
    </div>
    <?= $this->inlineScript() ?>
    </body>
    <!-- Scripts -->
    <?= $this->inlineScript()
        ->prependFile($this->basePath('build/' . $operator_js))
        ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
    //            ->prependFile($this->basePath('js/bootstrap.min.js'))
    ?>
    </html>

