<?= $this->doctype() ?>

    <html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="Content-Type" content="text/html; charset=windows-1251"/>

        <?= $this->headTitle('БрянскМАЗсервис')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
        ?>

    </head>
    <body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container bg-light mt-5 ">

        </div>
    </nav>

    <div class="container">
        <?= $this->content ?>
        <hr>
        <footer>
            <p>&copy; 2005 - <?= date('Y') ?> by БрянскМАЗсервис. All rights reserved.</p>
        </footer>
    </div>
    <?= $this->inlineScript() ?>
    </body>
    </html>

<?php
//$this->placeholder('content')->captureEnd();
//echo $this->partial('layout/layout',
//    ['content'=>$this->placeholder('content')]);
?>